# Generated by Django 4.1 on 2023-04-09 16:50

import backend.department.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='first_name')),
                ('middle_name', models.CharField(max_length=64, verbose_name='middle_name')),
                ('last_name', models.CharField(db_index=True, max_length=64, verbose_name='first_name')),
                ('position', models.CharField(help_text='Employee post.', max_length=128, verbose_name='position')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='salary')),
                ('photo', models.ImageField(upload_to=backend.department.utils.upload_to, verbose_name='photo')),
                ('age', models.IntegerField(verbose_name='age')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department', to='department.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ('id',),
            },
        ),
    ]
