# Generated by Django 4.1 on 2023-04-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_remove_department_employee_department_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='director',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='_department', to='department.employee', verbose_name='director'),
        ),
    ]
